CREATE DATABASE DB_NEWSMANAGER;
USE DB_NEWSMANAGER;

DROP TABLE IF EXISTS `NEWS`;
CREATE TABLE IF NOT EXISTS `NEWS` (
	`id` int( 11 ) NOT NULL AUTO_INCREMENT ,
	`titulo` varchar( 255 ) NOT NULL ,
	`conteudo` text NOT NULL ,
	`autor` varchar( 255 ) NOT NULL,
	`imagem` varchar( 255 ),
	PRIMARY KEY ( `id` )
) ENGINE=InnoDB DEFAULT CHARSET=latin1;)
